spring:
  application:
    name: yyzx
  datasource:
    url: jdbc:mysql://localhost:3307/health?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:com/neutech/mapper/*.xml
  type-aliases-package: com.neutech.entity
logging:
  level:
    com.neutech.mapper: debug
